SELECT
	(SELECT NAME
		FROM PERSON P
		WHERE P.ID = P_ORDER.PERSON_ID) AS NAME,
	(CASE 
		WHEN 
			(SELECT NAME FROM PERSON P WHERE P.ID = P_ORDER.PERSON_ID) = 'Denis'
		THEN 'true'
		ELSE 'false'
	END) AS CHECK_NAME
FROM PERSON_ORDER P_ORDER
WHERE (MENU_ID = 13 OR MENU_ID = 14 OR MENU_ID = 18)
	AND ORDER_DATE = '2022-01-07';